import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { homedir } from "node:os";
import { join } from "node:path";
import { ProfileStore } from "./store.js";
import { LearningEngine } from "./learning.js";
import { createExtractorFromEnv, observationsToInput } from "./extractor.js";
import { filterAutomaticObservations } from "./safety.js";
import { SessionManager, type ProfileSession } from "./session.js";
import { evaluateResponse } from "./eval.js";
import { renderContext } from "./render.js";
import { ProjectStore } from "./project-store.js";

const rootDir = process.env.PROFILE_PACK_DIR ?? join(homedir(), ".profile-pack");
const store = new ProfileStore(rootDir);
const result = (value: unknown) => ({ content: [{ type: "text" as const, text: JSON.stringify(value, null, 2) }] });
const resource = (uri: URL, value: unknown) => ({ contents: [{ uri: uri.href, mimeType: "application/json", text: JSON.stringify(value, null, 2) }] });

export function createServer(profileStore: ProfileStore, learning = new LearningEngine(profileStore.rootDir), sessions = new SessionManager(learning, createExtractorFromEnv())): McpServer {
  const server = new McpServer({ name: "profile-pack", version: "0.1.0" });
  const projects = new ProjectStore(profileStore.rootDir);
  server.registerTool("profile_status", { description: "Check whether the user's Profile Pack is empty and whether onboarding is required.", inputSchema: {} }, async () => result(await profileStore.status()));
  server.registerTool("initialize_profile", { description: "Initialize an empty Profile Pack with user-approved facts and preferences.", inputSchema: { items: z.array(z.object({ kind: z.enum(["fact", "preference", "goal", "constraint", "boundary", "trait"]), scope: z.string(), statement: z.string().min(1), sensitivity: z.enum(["normal", "sensitive", "high"]).default("normal"), confidence: z.number().min(0).max(1).default(1), evidenceCount: z.number().int().min(0).default(1) })), agentId: z.string().default("onboarding") } }, async ({ items, agentId }) => result(await profileStore.initialize(items, agentId)));
  server.registerTool("get_profile", { description: "Read a purpose-scoped, privacy-filtered view of the user's Profile Pack. Access is limited by the local agent policy.", inputSchema: { scopes: z.array(z.string()).default(["global"]), purpose: z.string().optional(), agentId: z.string().default("unknown"), token: z.string().optional(), includeSensitive: z.boolean().default(false) } }, async ({ scopes, purpose, agentId, token, includeSensitive }) => result(await profileStore.getView(scopes, agentId, purpose, includeSensitive, token)));
  server.registerTool("get_profile_context", { description: "Read a synthesized background context for implicit personalization. Prefer this over get_profile when raw Profile item fields are not needed. Do not quote the context as a Profile list.", inputSchema: { scopes: z.array(z.string()).default(["global"]), purpose: z.string().optional(), agentId: z.string().default("unknown"), token: z.string().optional(), includeSensitive: z.boolean().default(false) } }, async ({ scopes, purpose, agentId, token, includeSensitive }) => { const view = await profileStore.getView(scopes, agentId, purpose, includeSensitive, token); return result({ context: renderContext(view.profile, view.items), presentationPolicy: view.profile.presentationPolicy }); });
  server.registerTool("retrieve_decision_context", { description: "Retrieve only Profile evidence relevant to a decision request. This deterministic gate does not generate a recommendation and does not modify the Profile.", inputSchema: { goal: z.string().min(1), taskContext: z.string().optional(), constraints: z.array(z.string()).default([]), outputType: z.enum(["plan", "comparison", "prioritization", "recommendation", "custom"]).default("recommendation"), scopes: z.array(z.string()).default([]), taskType: z.string().optional(), agentId: z.string().default("unknown"), purpose: z.string().optional(), allowSensitive: z.boolean().default(false), token: z.string().optional() } }, async (request) => result(await profileStore.getDecisionContext(request)));
  server.registerTool("evaluate_decision_candidates", { description: "Evaluate 2-3 supplied decision candidates with a deterministic rule evaluator. It never modifies the Profile and always requires user confirmation.", inputSchema: { goal: z.string().min(1), taskContext: z.string().optional(), constraints: z.array(z.string()).default([]), outputType: z.enum(["plan", "comparison", "prioritization", "recommendation", "custom"]).default("recommendation"), scopes: z.array(z.string()).default([]), taskType: z.string().optional(), agentId: z.string().default("unknown"), purpose: z.string().optional(), allowSensitive: z.boolean().default(false), token: z.string().optional(), candidates: z.array(z.object({ id: z.string().min(1), title: z.string().min(1), summary: z.string().min(1), steps: z.array(z.string()).default([]), estimatedDays: z.number().positive().optional(), estimatedCost: z.string().optional(), risks: z.array(z.string()).default([]), assumptions: z.array(z.string()).default([]) })).min(2).max(3) } }, async ({ candidates, ...request }) => result(await profileStore.evaluateDecisionCandidates(request, candidates)));
  server.registerTool("create_project", { description: "Create an independent Project Profile accessible only to the creating Agent by default. This does not modify the personal Profile.", inputSchema: { name: z.string().min(1), description: z.string().optional(), goal: z.string().min(1), status: z.enum(["idea", "planned", "active", "paused", "completed", "archived"]).default("idea"), tags: z.array(z.string()).default([]), constraints: z.array(z.string()).default([]), agentId: z.string().default("unknown") } }, async ({ agentId, ...input }) => result(await projects.create({ ...input, allowedAgents: [agentId] }, agentId)));
  server.registerTool("list_projects", { description: "List Project Profiles visible to an Agent without returning full project contents.", inputSchema: { agentId: z.string().default("user") } }, async ({ agentId }) => result(await projects.list(agentId)));
  server.registerTool("get_project", { description: "Read one authorized Project Profile for project planning and updates.", inputSchema: { projectId: z.string().min(1), agentId: z.string().default("user"), purpose: z.string().default("project_context") } }, async ({ projectId, agentId, purpose }) => result(await projects.get(projectId, agentId, purpose)));
  server.registerTool("propose_project_update", { description: "Propose a Project Profile update. It is not applied until the user confirms it and the base version still matches.", inputSchema: { projectId: z.string().min(1), baseVersion: z.number().int().positive().optional(), patch: z.object({ name: z.string().optional(), description: z.string().optional(), goal: z.string().optional(), status: z.enum(["idea", "planned", "active", "paused", "completed", "archived"]).optional(), tags: z.array(z.string()).optional(), constraints: z.array(z.string()).optional(), milestones: z.array(z.object({ id: z.string(), title: z.string(), status: z.enum(["pending", "in_progress", "blocked", "done", "cancelled"]), dueAt: z.string().optional(), notes: z.string().optional() })).optional(), tasks: z.array(z.object({ id: z.string(), title: z.string(), status: z.enum(["pending", "in_progress", "blocked", "done", "cancelled"]), priority: z.enum(["low", "medium", "high"]).optional(), dueAt: z.string().optional(), notes: z.string().optional() })).optional(), decisions: z.array(z.object({ id: z.string(), title: z.string(), decision: z.string(), rationale: z.string().optional(), createdAt: z.string() })).optional(), risks: z.array(z.object({ id: z.string(), title: z.string(), severity: z.enum(["low", "medium", "high"]), mitigation: z.string().optional(), status: z.enum(["open", "mitigated", "accepted"]) })).optional() }), reason: z.string().optional(), evidence: z.array(z.string()).default([]), agentId: z.string().default("unknown") } }, async ({ projectId, baseVersion, patch, reason, evidence, agentId }) => result(await projects.propose(projectId, patch, agentId, baseVersion, reason, evidence)));
  server.registerTool("list_project_updates", { description: "List pending Project Profile updates awaiting user review.", inputSchema: { projectId: z.string().min(1), agentId: z.string().default("user") } }, async ({ projectId, agentId }) => result(await projects.listProposals(projectId, agentId)));
  server.registerTool("record_decision_feedback", { description: "Record a user's decision feedback without modifying the personal Profile or Project Profile automatically.", inputSchema: { projectId: z.string().min(1), goal: z.string().min(1), candidateIds: z.array(z.string()).default([]), recommendedCandidateId: z.string().optional(), action: z.enum(["accepted", "modified", "rejected", "regenerated"]), selectedCandidateId: z.string().optional(), modification: z.string().optional(), reason: z.string().optional(), evaluator: z.string().default("rule"), profileVersion: z.number().int().optional(), agentId: z.string().default("user") } }, async (entry) => result(await projects.recordDecision(entry)));
  server.registerTool("list_decision_log", { description: "Read decision feedback records for an authorized Project Profile.", inputSchema: { projectId: z.string().min(1), agentId: z.string().default("user") } }, async ({ projectId, agentId }) => result(await projects.listDecisions(projectId, agentId)));
  server.registerTool("list_agent_policies", { description: "List local Agent access policies. Sensitive item grants are returned as item IDs only.", inputSchema: {} }, async () => result(await profileStore.listAgentPolicies()));
  server.registerTool("authorize_sensitive_items", { description: "Grant one Agent access to selected sensitive Profile Pack item IDs. This does not expose values by itself; the Agent must request includeSensitive.", inputSchema: { agentId: z.string().min(1), itemIds: z.array(z.string()) } }, async ({ agentId, itemIds }) => result(await profileStore.setAgentSensitiveItems(agentId, itemIds)));
  server.registerTool("propose_profile_update", { description: "Submit a candidate profile update. It is not applied until the user confirms it.", inputSchema: { kind: z.enum(["fact", "preference", "goal", "constraint", "boundary", "trait"]), scope: z.string(), statement: z.string().min(1), sensitivity: z.enum(["normal", "sensitive", "high"]).default("normal"), confidence: z.number().min(0).max(1).default(0.5), evidenceCount: z.number().int().min(0).default(0), evidence: z.array(z.string()).default([]), agentId: z.string().default("unknown") } }, async ({ kind, scope, statement, sensitivity, confidence, evidenceCount, evidence, agentId }) => result(await profileStore.propose({ kind, scope, statement, sensitivity, confidence, evidenceCount }, agentId, evidence)));
  server.registerTool("list_pending_updates", { description: "List profile updates awaiting user review.", inputSchema: {} }, async () => result(await profileStore.listProposals()));
  server.registerTool("decide_profile_update", { description: "Confirm or reject a pending profile update.", inputSchema: { proposalId: z.string(), decision: z.enum(["confirm", "reject"]), reviewerId: z.string().default("user") } }, async ({ proposalId, decision, reviewerId }) => result(await profileStore.decideProposal(proposalId, decision, reviewerId)));
  server.registerTool("export_profile", { description: "Export a portable Profile Pack bundle for migration to another Agent. Sensitive fields are included only when explicitly requested by the user.", inputSchema: { scopes: z.array(z.string()).default([]), includeSensitive: z.boolean().default(false) } }, async ({ scopes, includeSensitive }) => result(await profileStore.exportBundle(scopes, includeSensitive)));
  server.registerTool("import_profile", { description: "Import a previously exported Profile Pack bundle. Existing items are preserved and duplicates are skipped.", inputSchema: { bundle: z.record(z.string(), z.unknown()), agentId: z.string().default("migration") } }, async ({ bundle, agentId }) => result(await profileStore.importBundle(bundle, agentId)));
  server.registerTool("record_profile_observation", { description: "Record a distilled observation. By default it remains Agent-specific until the same tendency is observed across Agents.", inputSchema: { scope: z.string(), dimension: z.string().min(1), value: z.string().min(1), statement: z.string().min(1), confidence: z.number().min(0).max(1).default(0.5), evidence: z.string().optional(), purpose: z.string().optional(), portability: z.enum(["portable", "agent_specific", "unknown"]).default("unknown"), agentId: z.string().default("unknown") } }, async ({ scope, dimension, value, statement, confidence, evidence, purpose, portability, agentId }) => result(await learning.observe({ scope, dimension, value, statement, confidence, evidence, purpose, portability, agentId })));
  server.registerTool("extract_profile_observations", { description: "Use the configured OpenAI-compatible or local Ollama model to extract conservative candidate observations from a conversation. Raw transcript is not stored.", inputSchema: { transcript: z.string().min(1), scope: z.string().default("global"), agentId: z.string().default("unknown") } }, async ({ transcript, scope, agentId }) => { const extractor = createExtractorFromEnv(); const filtered = filterAutomaticObservations(await extractor.extract(transcript, scope)); const results = []; for (const observation of filtered.accepted) results.push(await learning.observe(observationsToInput(observation, agentId))); return result({ extractedCount: filtered.accepted.length, blockedCount: filtered.blocked.length, blocked: filtered.blocked, results }); });
  server.registerTool("profile_reflect", { description: "Reflect on a completed task and add only safe, distilled observations to the learning queue. This is the recommended end-of-task hook.", inputSchema: { transcript: z.string().min(1), scope: z.string().default("global"), agentId: z.string().default("unknown") } }, async ({ transcript, scope, agentId }) => { const extractor = createExtractorFromEnv(); const filtered = filterAutomaticObservations(await extractor.extract(transcript, scope)); const results = []; for (const observation of filtered.accepted) results.push(await learning.observe(observationsToInput(observation, agentId))); return result({ reflected: true, extractedCount: filtered.accepted.length, blockedCount: filtered.blocked.length, blocked: filtered.blocked, results }); });
  server.registerTool("profile_session_start", { description: "Start a Profile Pack session. The host Agent should call this at the beginning of a task and use the returned synthesized context for implicit personalization. Do not quote individual Profile fields unless the user asks.", inputSchema: { agentId: z.string().default("unknown"), scope: z.string().default("global"), purpose: z.string().optional(), token: z.string().optional() } }, async ({ agentId, scope, purpose, token }) => { const session = sessions.start(agentId, scope, purpose); const view = await profileStore.getView([scope], agentId, purpose, false, token); return result({ session, context: renderContext(view.profile, view.items), presentationPolicy: view.profile.presentationPolicy }); });
  server.registerTool("profile_session_end", { description: "End a Profile Pack session and reflect on the completed task. Raw transcript is not stored; only safe distilled observations enter the learning queue.", inputSchema: { session: z.object({ sessionId: z.string(), agentId: z.string(), scope: z.string(), purpose: z.string().optional(), startedAt: z.string() }), transcript: z.string().min(1) } }, async ({ session, transcript }) => result(await sessions.end(session as ProfileSession, transcript)));
  server.registerTool("list_trait_candidates", { description: "List distilled user-trait candidates awaiting review.", inputSchema: {} }, async () => result(await learning.listCandidates()));
  server.registerTool("list_promotable_candidates", { description: "List candidates that have enough evidence and confidence to be promoted for user review.", inputSchema: { minEvidence: z.number().int().min(1).default(2), minConfidence: z.number().min(0).max(1).default(0.7) } }, async ({ minEvidence, minConfidence }) => result(await learning.listPromotableCandidates(minEvidence, minConfidence)));
  server.registerTool("get_learning_snapshot", { description: "Get candidates, effective confidence after time decay, promotion readiness, and open conflicts for review.", inputSchema: { minEvidence: z.number().int().min(1).default(2), minConfidence: z.number().min(0).max(1).default(0.7) } }, async ({ minEvidence, minConfidence }) => result({ candidates: await learning.listCandidateSummaries(minEvidence, minConfidence), conflicts: await learning.listConflicts() }));
  server.registerTool("evaluate_profile_response", { description: "Evaluate an Agent response for explicit profile references, single-attribute attribution, and sensitive leakage. Holistic use still requires human review.", inputSchema: { response: z.string().min(1), scopes: z.array(z.string()).default(["global"]), agentId: z.string().default("unknown") } }, async ({ response, scopes, agentId }) => { const profile = await profileStore.getProfile(); const view = await profileStore.getView(scopes, agentId, "response_evaluation"); return result(evaluateResponse(response, profile, view.items)); });
  server.registerTool("list_profile_versions", { description: "List immutable Profile Pack versions available for comparison or rollback.", inputSchema: {} }, async () => result(await profileStore.listVersions()));
  server.registerTool("compare_profile_versions", { description: "Compare two Profile Pack snapshots by added, removed, and changed items.", inputSchema: { fromVersion: z.number().int().min(1), toVersion: z.number().int().min(1) } }, async ({ fromVersion, toVersion }) => result(await profileStore.compareVersions(fromVersion, toVersion)));
  server.registerTool("rollback_profile", { description: "Restore an older Profile Pack snapshot as a new version. Existing history is preserved.", inputSchema: { version: z.number().int().min(1), agentId: z.string().default("user") } }, async ({ version, agentId }) => result(await profileStore.rollback(version, agentId)));
  server.registerTool("dismiss_trait_candidate", { description: "Dismiss a learned candidate so it will not be promoted.", inputSchema: { candidateId: z.string() } }, async ({ candidateId }) => result(await learning.dismissCandidate(candidateId)));
  server.registerTool("promote_trait_candidate", { description: "Turn a sufficiently supported trait candidate into a normal Profile proposal. The user must still confirm the resulting profile proposal.", inputSchema: { candidateId: z.string(), agentId: z.string().default("learning"), minEvidence: z.number().int().min(1).default(2), minConfidence: z.number().min(0).max(1).default(0.7) } }, async ({ candidateId, agentId, minEvidence, minConfidence }) => { const candidate = await learning.getCandidate(candidateId); if (candidate.status !== "candidate" || candidate.evidenceCount < minEvidence || candidate.confidence < minConfidence) throw new Error(`Candidate does not meet promotion threshold (evidence >= ${minEvidence}, confidence >= ${minConfidence})`); const proposal = await profileStore.propose({ kind: "trait", scope: candidate.scope, statement: candidate.statement, confidence: candidate.confidence, evidenceCount: candidate.evidenceCount }, agentId, candidate.observationIds); await learning.markPromoted(candidateId); return result({ candidate, proposal }); });
  server.registerTool("list_trait_conflicts", { description: "List possible conflicts where Agents observed different values for the same user dimension and scope.", inputSchema: {} }, async () => result(await learning.listConflicts()));
  server.registerTool("resolve_trait_conflict", { description: "Record the user's decision for a trait conflict. This MVP records the decision; promotion into the official profile remains an explicit confirmation step.", inputSchema: { conflictId: z.string(), resolution: z.enum(["keep_left", "keep_right", "keep_both", "dismiss"]) } }, async ({ conflictId, resolution }) => result(await learning.resolveConflict(conflictId, resolution)));
  server.registerResource("profile-status", "profile://status", { description: "Current Profile Pack state and onboarding status.", mimeType: "application/json" }, async (uri) => resource(uri, await profileStore.status()));
  server.registerResource("presentation-policy", "profile://presentation-policy", { description: "User's preferred implicit personalization policy.", mimeType: "application/json" }, async (uri) => resource(uri, (await profileStore.getProfile()).presentationPolicy));
  return server;
}

if (process.argv[1]?.endsWith("/mcp.ts") || process.argv[1]?.endsWith("/mcp.js")) {
  await store.ensure();
  const learning = new LearningEngine(rootDir);
  await learning.ensure();
  await new ProjectStore(rootDir).ensure();
  await createServer(store, learning).connect(new StdioServerTransport());
}
